### ISSUE TITLE
Pincode boundaries data seems noisy

### ISSUE THREAD

**Issue by nikhil-scholarlify** [ramSeraph/indian_admin_boundaries#1]
Thanks for all this amazing work!  Just flagging an example case here.

https://github.com/ramSeraph/indian_admin_boundaries/releases/tag/postal 

Preview link over Pune: https://indianopenmaps.fly.dev/not-so-open/pincodes/view#11.41/18.5303/73.8397

Many of the polygons aren't carrying any pincode value.
And most of Pune city is covered by a single polygon with value: 411045. That's certainly not the case.

![image](https://github.com/ramSeraph/indian_admin_boundaries/assets/151929870/f3b36099-48c6-4ae9-930a-cc7aecb08d15)

**Comment by ramSeraph** [comment]
Hey.. maybe I should have clarified. This is what I could find on the postalgis site. This is just raw data. I didn't clean anything. That goes for all the data in this repo.

**Comment by ramSeraph** [comment]
I actually want to check if we are just looking at the village boundaries with pincode tagged to them. Anyway I will try add notes with your feedback atleast

**Comment by ramSeraph** [comment]
I did check the pincode boundaries against village boundaries.. they have common borders but they are not the same. 

And I have updated the notes for pincode boundaries to reflect your feedback.

**Comment by ramSeraph** [comment]
Closing as nothing more can be done on my part and documentation has been updated to reflect the feedback
